gui:
  # Carbonfox color theme
  theme:
    lightTheme: false
    activeBorderColor:
      - '#78a9ff'
      - bold
    inactiveBorderColor:
      - '#393939'
    optionsTextColor:
      - '#b6b8bb'
    selectedLineBgColor:
      - '#282c34'
    cherryPickedCommitBgColor:
      - '#ee5396'
    cherryPickedCommitFgColor:
      - '#161616'
    unstagedChangesColor:
      - '#ff8389'
    defaultFgColor:
      - '#f2f4f8'
  
  # Basic UI preferences
  showListFooter: true
  showFileTree: true
  showRandomTip: false
  showCommandLog: false
  
  # Commit length
  commitLength:
    show: true

# Git configuration
git:
  # Auto-fetch and refresh
  autoFetch: true
  autoRefresh: true
  
  # Pulling preference
  pull:
    mode: 'rebase'
  
  # Log display
  log:
    order: 'topo-order'
    showGraph: 'when-maximised'

# Disable update checks
update:
  method: never

# Editor preference
os:
  editCommand: 'nvim'
